### ISSUE TITLE
AttributeError: module 'openai' has no attribute 'ChatCompletion'

### ISSUE THREAD

**Issue by MrBenzWorld** [logankilpatrick/ChatGPT-Simple#2]
AttributeError: module 'openai' has no attribute 'ChatCompletion'

**Comment by ahmadmustafaanis** [comment]
`pip install --upgrade openai`

**Comment by ParkerRex** [comment]
Traceback (most recent call last):
  File "/Users/parkerrex/Developer/ChatGPT-Simple/server.py", line 3, in <module>
    import openai
ModuleNotFoundError: No module named 'openai'

**Comment by ahmadmustafaanis** [comment]
@ParkerRex follow the readme, you need to install the packages. `pip install -r requirements.txt`
